name: Main
on: push
jobs:
  shellcheck:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ShellCheck
        uses: moorara/actions/shellcheck@master
